version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    nodejs: '18'
  apt_packages:
    - libarchive-dev
  jobs:
    pre_build:
      - python -m pip install -r requirements-dev.txt
      - jlpm --frozen-lockfile
      - jlpm build:prod
      - jlpm dev
      - jlpm dist
      # pre-build the lite site to isolate build errors
      - jlpm docs:lite

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
