[build-system]
requires = ["hatchling>=1.11"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "prompt_toolkit/__init__.py"

[project]
name = "prompt_toolkit"
authors = [
    {name = "JupyterLite Contributors"},
]
dependencies = [
    "wcwidth",
]
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version", "description"]
classifiers = [
    "License :: OSI Approved :: BSD License",
]

[project.urls]
Source = "https://github.com/jupyterlite/pyodide-kernel"
