name: Test

on:
  push:
    branches: main
  pull_request:
    branches: '*'

env:
  RTD_WHEEL: https://jupyterlite.rtfd.io/en/latest/_static/jupyterlite-0.1.0b18-py3-none-any.whl

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ['3.8', '3.11']
        node-version: ['18']

    env:
      CACHE_PREFIX: ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install Python dependencies
        run: python -m pip install -v -e ".[dev,test]"

      # TODO: remove
      - name: Install JupyterLite from ReadTheDocs
        run: python -m pip install -v --force-reinstall ${{ env.RTD_WHEEL }}

      - name: Install JS dependencies
        run: jlpm --frozen-lockfile

      - name: Build JS extension
        run: jlpm build:prod

      - name: Install JS extension
        run: jupyter labextension develop . --overwrite

      - name: Run the tests
        run: pytest

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: |-
            jupyterlite-pyodide-kernel-pytest-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.python-version}}
          path: build/reports
          if-no-files-found: error
